#!/usr/bin/env python3
"""
Interactive HaromaX6 deployment wizard — writes a project-root ``.env`` file.

Usage (from repository root)::

    python scripts/setup_wizard.py

Optional: ``--profile 1|2|3|4`` pre-selects the profile (you still confirm values).

* [1] Local development — bind 127.0.0.1, no bearer, no rate limit
* [2] LAN server — 0.0.0.0, bearer, rate limit, structured log
* [3] Robot / edge — like LAN + higher rate limit + bridge URL hint
* [4] Custom — LAN-ish defaults, you choose bearer/rate limits
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys


def _root() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _prompt(msg: str, default: str | None = None) -> str:
    hint = f" [{default}]" if default is not None else ""
    raw = input(f"{msg}{hint}: ").strip()
    if not raw and default is not None:
        return default
    return raw


def _prompt_yes(msg: str, default: bool = True) -> bool:
    d = "Y/n" if default else "y/N"
    raw = input(f"{msg} ({d}): ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes", "1", "true", "on")


def _prompt_int(msg: str, default: int, lo: int, hi: int) -> int:
    while True:
        raw = _prompt(msg, str(default))
        try:
            v = int(raw)
            if lo <= v <= hi:
                return v
        except ValueError:
            pass
        print(f"  Enter an integer between {lo} and {hi}.")


def _profile_defaults(choice: str) -> dict:
    if choice == "1":
        return {
            "HAROMA_BIND_HOST": "127.0.0.1",
            "HAROMA_HTTP_PORT": "8193",
            "bearer_mode": "none",
            "HAROMA_HTTP_RATE_LIMIT_PER_MIN": "0",
            "HAROMA_STRUCTURED_LOG": "0",
            "HAROMA_ROBOT_CLIENT_URL": "",
        }
    if choice == "2":
        return {
            "HAROMA_BIND_HOST": "0.0.0.0",
            "HAROMA_HTTP_PORT": "8193",
            "bearer_mode": "generate",
            "HAROMA_HTTP_RATE_LIMIT_PER_MIN": "120",
            "HAROMA_STRUCTURED_LOG": "1",
            "HAROMA_ROBOT_CLIENT_URL": "",
        }
    if choice == "3":
        return {
            "HAROMA_BIND_HOST": "0.0.0.0",
            "HAROMA_HTTP_PORT": "8193",
            "bearer_mode": "generate",
            "HAROMA_HTTP_RATE_LIMIT_PER_MIN": "240",
            "HAROMA_STRUCTURED_LOG": "1",
            "HAROMA_ROBOT_CLIENT_URL": "http://127.0.0.1:8193",
        }
    return {
        "HAROMA_BIND_HOST": "0.0.0.0",
        "HAROMA_HTTP_PORT": "8193",
        "bearer_mode": "ask",
        "HAROMA_HTTP_RATE_LIMIT_PER_MIN": "0",
        "HAROMA_STRUCTURED_LOG": "0",
        "HAROMA_ROBOT_CLIENT_URL": "",
    }


def _write_env(path: str, lines: list[tuple[str, str]]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by scripts/setup_wizard.py — edit as needed.\n")
        for k, v in lines:
            if v == "":
                f.write(f"# {k}=\n")
            else:
                safe = v.replace("\\", "\\\\").replace("\n", "\\n")
                if any(c in safe for c in ' "\'`'):
                    f.write(f'{k}="{safe}"\n')
                else:
                    f.write(f"{k}={safe}\n")


def main() -> int:
    ap = argparse.ArgumentParser(description="HaromaX6 interactive setup wizard")
    ap.add_argument(
        "--profile",
        choices=("1", "2", "3", "4"),
        default=None,
        help="Pre-selected profile (default: ask)",
    )
    ap.add_argument(
        "-y",
        "--yes",
        action="store_true",
        help="Overwrite existing .env without confirmation",
    )
    args = ap.parse_args()

    root = _root()
    env_path = os.path.join(root, ".env")
    print("\n=== HaromaX6 setup wizard ===\n")
    print("Choose a deployment profile:\n")
    print("  [1] Local development  — bind 127.0.0.1, no bearer, no rate limit")
    print("  [2] LAN server         — bind 0.0.0.0, bearer token, rate limit, structured log")
    print("  [3] Robot / edge       — like LAN + higher rate limit + bridge URL hint")
    print("  [4] Custom             — prompt for bearer/rate limits with open bind\n")

    choice = args.profile or _prompt("Profile (1-4)", "1")
    if choice not in ("1", "2", "3", "4"):
        print("Invalid choice; using [1] local development.")
        choice = "1"

    d = _profile_defaults(choice)

    print("\n--- Listen address ---\n")
    d["HAROMA_BIND_HOST"] = _prompt(
        "Bind host (127.0.0.1 = local only; 0.0.0.0 = all interfaces)",
        d["HAROMA_BIND_HOST"],
    )
    d["HAROMA_HTTP_PORT"] = str(
        _prompt_int("HTTP port", int(d["HAROMA_HTTP_PORT"]), 1, 65535)
    )

    print("\n--- HTTP security & logging ---\n")
    bearer_val = ""
    bm = d["bearer_mode"]
    if bm == "generate":
        if _prompt_yes("Generate a random HAROMA_HTTP_BEARER_TOKEN?", True):
            bearer_val = secrets.token_urlsafe(24)
            print(f"  Token (save this): {bearer_val}")
        else:
            bearer_val = _prompt("Paste bearer token (empty = none)", "")
    elif bm == "none":
        if _prompt_yes("Set a bearer token anyway (recommended if not localhost-only)?", False):
            if _prompt_yes("Generate random token?", True):
                bearer_val = secrets.token_urlsafe(24)
                print(f"  Token (save this): {bearer_val}")
            else:
                bearer_val = _prompt("Bearer token", "")
    else:
        if _prompt_yes("Set HAROMA_HTTP_BEARER_TOKEN?", False):
            if _prompt_yes("Generate random token?", True):
                bearer_val = secrets.token_urlsafe(24)
                print(f"  Token (save this): {bearer_val}")
            else:
                bearer_val = _prompt("Bearer token", "")

    d["HAROMA_HTTP_RATE_LIMIT_PER_MIN"] = str(
        _prompt_int(
            "Max POST requests / minute / IP / route (0 = off)",
            int(d["HAROMA_HTTP_RATE_LIMIT_PER_MIN"]),
            0,
            100000,
        )
    )
    struct_default = d["HAROMA_STRUCTURED_LOG"] == "1"
    d["HAROMA_STRUCTURED_LOG"] = (
        "1"
        if _prompt_yes("Enable structured JSON access logs (HAROMA_STRUCTURED_LOG)?", struct_default)
        else "0"
    )

    print("\n--- Robot bridge (optional) ---\n")
    print("HAROMA_ROBOT_CLIENT_URL helps bridge scripts know where to POST (set on the robot).\n")
    ru = _prompt(
        "Base URL of this Haroma server (empty to skip)",
        d.get("HAROMA_ROBOT_CLIENT_URL") or "",
    )

    lines: list[tuple[str, str]] = [
        ("HAROMA_BIND_HOST", d["HAROMA_BIND_HOST"]),
        ("HAROMA_HTTP_PORT", d["HAROMA_HTTP_PORT"]),
        ("HAROMA_HTTP_RATE_LIMIT_PER_MIN", d["HAROMA_HTTP_RATE_LIMIT_PER_MIN"]),
        ("HAROMA_STRUCTURED_LOG", d["HAROMA_STRUCTURED_LOG"]),
    ]
    if bearer_val:
        lines.insert(2, ("HAROMA_HTTP_BEARER_TOKEN", bearer_val))
    if ru:
        lines.append(("HAROMA_ROBOT_CLIENT_URL", ru))

    if os.path.isfile(env_path) and not args.yes:
        if not _prompt_yes(f"\nOverwrite existing {env_path}?", False):
            print("Aborted.")
            return 1

    _write_env(env_path, lines)
    print(f"\nWrote: {env_path}\n")
    print("Next steps:")
    print(f"  cd {root}")
    print("  python main.py")
    if bearer_val:
        print("\nProtected routes: send Authorization: Bearer <token> or X-Haroma-Token")
    if ru:
        print(f"\nOn the robot: export HAROMA_URL={ru}  (see bridge/sample_http_bridge.py)")
    print("\nDocs: docs/getting-started.md, docs/robot-integration.md\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
